#
# CSE183 Assignment 8 Backend
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 8 Backend
  version: 0.1.0
  title: CSE183 Assignment 8 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /dummy:
    get:
      description: Dummy Endpoint
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DummyResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /dms:
    get:
      description: Return all unique DMstreams, along with messages within each stream.
      responses:
        200:
          description: Success. Retrieved all dmstreams.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllDMs'
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    DummyResponse:
      required:
        - message
      properties:
        message:
          type: string

    AllDMs:
      type: array
      items:
        $ref: '#/components/schemas/SingleDMStream'
    
    SingleDMStream:
      type: array
      items:
        $ref: '#/components/schemas/Message'

    Message:
      type: object
      properties:
        from:
          type: string
          default: 'name'
        content:
          type: string
          default: 'content'
      required:
      - from
      - content
    
    
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

security:
  - bearerAuth: []         # use the same name as above